### PR TITLE
Fix map printer and add example project

### PR DESCRIPTION
**Pull request by adakitesystems**
With the initial removal of the EasyBMP dependency, the map printer had no way to generate image files. This PR re-enables map printing support with a private nested class stitched together from [MIG](https://github.com/adakitesystems/mig) for image writing.

An example project has also been added to demonstrate BWEM's map and map printer initialization.

**Note:** MIG (EasyBMP's replacement) depends on `stb_image_write.h` which is **NOT** included in this PR. Users must obtain this dependency themselves or it could be added as a submodule?

Fighting Spirit example printout:
map

### CODE REVIEW

**Comment by N00byEdge** [comment]
Okay that's a fair point, I just thought this PR didn't cover that part too. On the `.gitignore`, were there files that should be ignored which were with that? I thought the `.gitignore` we had now covered any such files.

**Comment by kant2002** [comment]
@adakitesystems maybe you could provide and mapPrinter.vcxproj so people just immediately could build application and check how it is working.

**Comment by adakitesystems** [comment]
@N00byEdge,
> On the .gitignore, were there files that should be ignored which were with that?

With the original .gitignore, Git is not ignoring the following:
```
examples/ExampleAIModule/.vs/
examples/ExampleAIModule/ExampleAIModule.vcxproj.user
```
I can see `/.vs` in the original `.gitignore` but this only ignores `.vs` when it is in the root directory. With the newly added example project, its `.vs` is not ignored in the ExampleAIModule directory. I realize it would be an easy fix to change `/.vs` to `.vs/` and also add `*.user`, but I used the `VisualStudio.gitignore` from that repo since they seem to actively update it to ignore all irrelevant temp/build/user-specific files. I'll revert the `.gitignore` commit in this PR.

@kant2002,
> @adakitesystems maybe you could provide and mapPrinter.vcxproj so people just immediately could build application and check how it is working.

Please clarify your suggestion. The added `ExampleAIModule` project already compiles into `ExampleAIModule.dll` which generates that sample image I posted above when run with BWAPI 4.2.0 + vanilla BW. Are you talking about creating a project that can be run with OpenBW that is similar to your tests? Or maybe some sort of standalone map printer executable? What are you looking for in terms of a `mapPrinter.vcxproj` that is not already in the `ExampleAIModule`?

**Comment by adakitesystems** [comment]
I removed the `.gitignore` commit.

**Comment by kant2002** [comment]
@adakitesystems I thought that you made changes in examples/examples.cpp to make standalone application which print map. But after your comment I realize that you do such example in the AI module. And you even could not do such application without bring OpenBW as dependency.

Another small thing is that, could you please separate style changes in the separate PR, at least it would be easier to review functional changes with style changes.

**Comment by adakitesystems** [comment]
@kant2002,
> Another small thing is that, could you please separate style changes in the separate PR, at least it would be easier to review functional changes with style changes.

What style changes? I did not make any style changes other than the `.gitignore` commit which I already removed. Are you talking about adding `BWAPI::` and `std::` to some objects? A lot of `using namespace` usages were removed by someone else before this PR.

The map printer in your repo does not work or compile at all with the `BWEM_USE_MAP_PRINTER` preprocessor macro. Any changes I made were to get the map printer working. The example project shows how to use the map printer. Without the example project, it is not so clear how to use the map printer with the `examples.cpp`.

I consider the map printer extremely valuable. However, the intent of this PR does not seem clear to others. In that case, I think it might be better to ignore or close this PR.

**Comment by kant2002** [comment]
@adakitesystems  Yes, I do talk about adding `BWAPI::` and `std::`, I understand that change is probably to fix compilation error and made change consistent with codebase. My request is more ask for made separate change in the future, or at least mention rationale. When seeing stylistically changes, I always ask myself, is there small fix lying somewhere in between noise of adding changing formatting. I think we on the same page about this change now.

**Pull request merged**
