### PR TITLE
Removed buildability dictating altitude of mini tiles

### PR DESCRIPTION
**Pull request by Cmccrave**
This generates the behavior we expect after BWAPI 4.4.0 fixed buildable tile checks under doodads.

### CODE REVIEW

**Review by N00byEdge — CHANGES_REQUESTED** [review]
The test cases for the expected heights are failing. I would appreciate if you updated those with this PR.

Example: https://ci.appveyor.com/project/N00byEdge/bwem-community/builds/26415334/job/nsm3h7xqilcnum7r#L508

**Comment by Cmccrave** [comment]
Found a new solution that better represents the idea of altitude and walkability of minitiles, it should not be affecting altitude and should be functioning no different from BWAPI 4.2.0

**Comment by Cmccrave** [comment]
This should work correctly now. I pushed the wrong one first time, but this one should have identical altitudes from 4.2.0 to 4.4.0.

**Comment by N00byEdge** [comment]
When you say they have different values, are you doing tests on your own locally?

For unit tests, we use OpenBW/BWAPI with 4.2.0, just so you know. So you're comparing 4.2.0 walkability to 4.2.0 buildability if you're just looking at the test results.

**Comment by Cmccrave** [comment]
I am testing locally as well, but using the tests to verify that altitude hasn't changed for 4.2.0. Goal here is to have identical altitude values between 4.2.0 and 4.4.0, without losing information about actual walkable/buildable tiles.

**Comment by Cmccrave** [comment]
Requesting to merge this in without unit tests passing, since the unit tests won't actually match this due to the change in doodad buildability being corrected in BWAPI 4.4.

**Pull request merged**
